#!/usr/bin/env bash
#display the content of /etc/passwd containing the username, user id, home directory
filename='/etc/passwd'
while read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < $filename
