#!/usr/bin/env bash
#create a story out of /etc/passwd file

while IFS=: read -r name pass U_ID G_ID GECOS HD SH_NAME
do
	echo "The user $name is part of the $G_ID gang, lives in $HD and rides $SH_NAME. $U_ID's place is protected by the passcode $pass, more info about the user here: $GECOS"
done < /etc/passwd
