#!/usr/bin/env bash
#A Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

declare -i idx=0
while (( idx < 10 ))
do
    echo "Best School"
    if (( idx == 8 ))
	then
	echo "Hi"
	fi
    (( idx++ ))
done
