#!/usr/bin/env bash
#prints Best School 10x, if 9 print Hi at the next line

i=0
while (( i < 10 ))
do
	if (( i==8 ))
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( i++ ))
done
