#!/usr/bin/env bash
#print Best school, at loop 4, print bad luck, at loop 8 good luck
i=0
while (( i<10 ))
do
	if (( i==3 ))
	then
		echo "bad luck"
	elif (( i==7 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
