#!/usr/bin/env bash
#A Bash script that loops from 1 to 10 and:
#	- displays bad luck for the 4th loop iteration
#	- displays good luck for the 8th loop iteration
#	- displays Best School for the other iterations

declare -i idx=0
while (( idx < 10 ))
do
    if ((idx == 3))
    then 
	echo "bad luck"
    elif ((idx == 7))
    then 
	echo "good luck"
    else
	echo "Best School"
    fi
      ((idx++))
done
