#!/usr/bin/env bash
#print up to 20 with while loop and case statement
i=1
while (( i<=20 ))
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China" ;;
		9)
			echo "$i"
			echo "bad luck from Japan" ;;
		17)
			echo "$i"
			echo "bad luck from Italy" ;;
		*)
			echo "$i" ;;
	esac
	(( i++ ))
done
