#!/usr/bin/env bash
#A Bash script that displays the time for 12 hours and 59 minutes:
#	- display hours from 0 to 12
#	- display minutes from 1 to 59

declare -i hour=0
declare -i minute

while ((hour < 13))
do 
   echo "Hour: $hour"
   minute=1
   while ((minute < 60))
   do
        echo "$minute"
	((minute++))
   done
   ((hour++))
done