#!/usr/bin/env bash
#print the clock digits
i=1
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	while [ $i -le 59 ]
	do
		if [ $i -eq 59 ]
		then
			echo "$i"
			i=1
			break
		else
			echo "$i"
		fi
		(( i++ ))
	done
	(( hour++ ))
done
