#!/usr/bin/env bash
#A Bash script that displays:
#	- The content of the current directory
#	- In a list format
#	- Where only the part of the name after the first dash is displayed (refer to the example)

for file_name in *
do
	echo "$file_name" | cut -d "-" -f2-
done