#!/usr/bin/env bash
#script that gives information about school
name="school"
if [ -e $name ]
then
	echo "$name file exists"
	if [ -s $name ]
	then
		echo "$name file is not empty"
		if [ -f $name ]
		then
			echo "$name is a regular file"
		fi
	else
		echo "$name file is empty"
		if [ -f $name ]
		then
			echo "$name is a regular file"
		fi
	fi
else
	echo "$name file does not exist"
fi
